name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "db"
database_id = "ISI_ID_D1_NANTI"

[[kv_namespaces]]
binding = "kv"
id = "6dee9e240dc54e8ea16c163eae69b59f"

#[[r2_buckets]]
#binding = "r2"
#bucket_name = ""

#[[send_email]]
#name = "email"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["*/30 * * * *", "0 16 * * *"]

[vars]
#ai_model = ""
#analysis_cache = false
#orm_log = false
domain = ["garokvpn.my.id"]
admin = "admin@garokvpn.my.id"
jwt_secret = "GarokSecretKey2026"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
